
project_id = "nlrxzpszbkifkkuyfinx"
api_host = "api.supabase.com"
functions_host = "functions.supabase.com"

[functions.send-contact-email]
verify_jwt = false

[functions.generate-image]
verify_jwt = true

[functions.generate-video]
verify_jwt = true

[functions.generate-transcript]
verify_jwt = true

[functions.check-video-status]
verify_jwt = true
